### PR TITLE
added another unit

### PR DESCRIPTION
**Pull request by rdemel**
Done

### CODE REVIEW

**Review by ala1705 — APPROVED** [review]

**Comment by rdemel** [comment]
@ala1705 thank you

**Comment by rdemel** [comment]
@mghosh00 check units for luminance- Ala's comment, not mine, lol just the messenger

**Comment by mghosh00** [comment]
@ala1705 you fix it if you're so bothered about it

**Comment by mghosh00** [comment]
Also I've already closed issue #1

**Pull request merged**
